version: '3'
services:
  web:
    image: nginx:1.17.1
    container_name: web-symfony
    ports:
      - 8080:80
    restart: "no"
    volumes:
      - .:/app
      - .docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - default
      - nginx-proxy

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: php-symfony
    restart: "no"
    volumes:
      - .:/app
      - .docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db-symfony
    restart: "no"
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      - ./DB/:/home/mysqlData

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-symfony
    restart: "no"
    volumes:
      - .docker/phpmyadmin/php.ini:/usr/local/etc/php/php.ini
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 9110:80
    links:
      - db

volumes:
  db_data:

networks:
  nginx-proxy:
    external: true

